version: "2"

# networks:
#   test:

networks:
  basic-network:
    external: true

services:
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.4.2
    # dns_search: .
    environment:
      - CALIPER_BIND_SUT=fabric:2.2.3
      - CALIPER_BENCHCONFIG=/hyperledger/caliper/workspace/benchmarks/benchmark-config.yaml
      - CALIPER_NETWORKCONFIG=/hyperledger/caliper/workspace/networks/network-config.yaml
      - CALIPER_WORKSPACE=/hyperledger/caliper/workspace
      - CALIPER_FABRIC_GATEWAY_ENABLED="true"
      - CALIPER_FLOW_ONLY_TEST="true"
      - CALIPER_FABRIC_GATEWAY_LOCALHOST="false"
    working_dir: /hyperledger/caliper/workspace
    command: launch manager
    ports:
      - 8090:8090
    networks:
      - basic-network
    volumes:
      - ./benchmarks/:/hyperledger/caliper/workspace/benchmarks
      - ./networks/:/hyperledger/caliper/workspace/networks
      - ../BasicNetwork-my-version/crypto-config/:/hyperledger/caliper/crypto-config
