test:
    name: basic-contract-benchmark
    description: test benchmark with basic-asset-transfer
    workers:
      type: local
      number: 1
      # rateControl: 
      #   type: benchmarks/fixedRate.js
      #   opts:
      #     tps: 10
      #   type: fixed-load
      #   opts:
      #     transactionLoad: 2
      #   type: benchmarks/fixedLoadRate.js
      #   opts:
      #     transactionLoad: 10
      #   type: benchmarks/normalDistributionRate.js
      #   opts:
      #     standardDeviation: 5
      #     mean: 100
    rounds:
      - label: writeAsset
        description: Write asset benchmark - 30 tps
        txDuration: 1000
        rateControl:
          type: fixed-rate
          opts:
            tps: 30
        workload:
          module: workload/writeAsset.js
          arguments:
            assets: 10
            contractId: basic
      - label: writeAsset
        description: Write asset benchmark - 35 tps
        txDuration: 1000
        rateControl:
          type: fixed-rate
          opts:
            tps: 35
        workload:
          module: workload/writeAsset.js
          arguments:
            assets: 10
            contractId: basic